site_name: Machine Translation for Indigenous Language Preservation
theme:
  logo: null
  name: material
  custom_dir: docs/overrides
  palette:
    scheme: light 
    primary: red
    accent: pink  
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.indexes
    - toc.integrate
    - header.hidden

extra:
  homepage: index.md
  generator: false
  
extra_css:
- overrides/custom.css

plugins: []
